### PR TITLE
Add `get_client` and `_create_bucket` methods to `GCloudBlobStore`

### PR DESCRIPTION
**Pull request by vangheem**

### CODE REVIEW

**Review by gitcarbs — APPROVED** [review]

**Review by bloodbare — COMMENTED** [review]
Wouldn't it be better that the client is defined globaly on the utility so doesnt need to be  created everytime ?

**Comment by vangheem** [comment]
Currently, it's created every time so I didn't change that part. I can change it if you prefer.

It's only used when a bucket is created though.

**Comment by bloodbare** [comment]
I would see it more cleaner with a cached client property so its not created everytime a storage is created (as we are introducing get_client func)

**Comment by vangheem** [comment]
done.

**Comment by bloodbare** [comment]
Thanks!

**Review by bloodbare — APPROVED** [review]

**Pull request merged**
